# Generated by Django 4.2.3 on 2023-07-26 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movies',
            new_name='List',
        ),
    ]
