# Generated by Django 4.2.3 on 2023-07-26 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0003_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='username',
        ),
    ]
